# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: CBMC dependencies
      run: |
        sudo apt-get install g++ gcc flex bison make git libwww-perl patch git
        
    - name: Tool dependencies
      run: |
        sudo apt-get install python3 cvc4 cbmc z3
    
    - name: Cache fastsynth
      id: cache-fastsynth
      uses: actions/cache@v1.2.0
      with:
        path: ./fastsynth
        key: ${{ runner.os }}-fastsynth
      
    - name: Fastsynth Setup
      if: steps.cache-fastsynth.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/kroening/fastsynth.git
        cd fastsynth
        git reset --hard b8841e05ef97a35d28fb097fa0e19cc998021997
        git submodule init
        git submodule update
        cd lib/cbmc
        make -C src minisat2-download
        make -C src
        cd ../../src
        make
        export PATH=$PATH:$(pwd)/fastsynth

    - name: Python modules
      run: |
        sudo apt-get install graphviz libgraphviz-dev pkg-config python3-pip python3-setuptools
        pip3 install numpy pygraphviz transitions termcolor
        
    - name: Run benchmarks
      run: |
        python3 run.py -gen_o incr
        python3 run.py -gen_o dfa
